### ISSUE TITLE
Test failing: laser::rate::tests::test_calculate_rate_coefficients_system

### ISSUE THREAD

**Issue by ElliotB256** [TeamAtomECS/AtomECS#21]
Hey @MauriceZeuner ,

Could you check and fix this unit test? It's been broken since I fixed the scattering rates, so I'm confident it's the test is outdated rather than the implementation (for instance, the integration test for scattering rate is working fine and agrees with the analytic formulae).

Cheers!

**Comment by ElliotB256** [comment]
I've set up CI for the repository now we are public, so please feel free to push the fix for the test directly to master.

**Comment by MauriceZeuner** [comment]
Hi Elliot,

will do that tomorrow, brain still too mushy today - what is a CI?

Best,
Maurice

Am Mo., 29. März 2021 um 22:54 Uhr schrieb ElliotB256 <
***@***.***>:

**Comment by ElliotB256** [comment]
If you look at the landing page, you'll notice we now have an 'x' which indicates the unit tests are failing. It's set to run them when the master branch is pushed or there is a pull request.

**Comment by ElliotB256** [comment]
Once this is fixed I'll tag it as v1.0.0 and make a release

**Comment by MauriceZeuner** [comment]
Okay, I fixed it. The problem was due to the 2pi problem we had with the linewidth and all and also another factor of 2 wrong.

The unit test green light is now on. :)

**Comment by ElliotB256** [comment]
hooray!
