### ISSUE TITLE
Heating for limited time-steps in ODT

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#25]
I have discovered that the length of the integration time-step has a very significant effect on the "numerical" heating in a dipole trap. I attached a picture, showing the simulation results of 3 (otherwise identical) simulations with:

- blue: 0.1 µs
- yellow: 1 µs
- red: 2 µs (only a few atoms left ^^)

![image](https://user-images.githubusercontent.com/73487591/113722591-7ab20c00-96e8-11eb-97df-fbf157fe3adc.png)

as the delta - timestep. They started with 100 atoms and ran for a total real time of 0.2 seconds each.
As you can see from the picture, for ODT one should choose a smaller timestep than in a MOT setup. I just felt this is something to be aware of. I'll try to find the largest time-step with negligible heating over a couple of seconds. Any comments?

**Comment by ElliotB256** [comment]
First up - what is your expected trap frequency?

Most likely thing is a bug with the velocity-verlet because it should be symplectic for a position-dependent force. @d-garrick

**Comment by MauriceZeuner** [comment]
Hey, you're on vacation, said so yourself! So please, answer this only when you really don't have anything better to do or your holidays are over ^^

Trap frequency: We have a horizontal, cross dipole trap (orthogonal) with identical beams of 1064nm, 10 W of power each and a waist of 100µm. For that, I calculate a trap depth of about 34 µK 
<img src="https://user-images.githubusercontent.com/73487591/113828363-353f1e80-977c-11eb-9fb0-c00c246db318.png" width="500">
and the following trap frequencies from the harmonic fit:
<img src="https://user-images.githubusercontent.com/73487591/113828541-6c153480-977c-11eb-8e34-60e7710e9449.png" width="500">
(meaning, along the two beams (in x and y): 182 Hz and along the z-direction 258 Hz)
Furthermore, to give you a better sense of scale for the above simulation result, one grid cell there is 50µm x 50 µm, atom sizes obviously far too large.

If it really was a bug of the integration system, that would indeed explain this... Any idea, where to start looking?

**Comment by MauriceZeuner** [comment]
I'm comparing velocity-verlet to EulerIntegrationSystem:

- dark blue: Velocity Verlet at 0.1 µs step-size
- light blue: Velocity Verlet at 1 µs step size
- red: Euler at 0.1 µs
- orange: Euler at 1 µs

![image](https://user-images.githubusercontent.com/73487591/113832116-33775a00-9780-11eb-883f-e41322834a8a.png)
![image](https://user-images.githubusercontent.com/73487591/113832536-9bc63b80-9780-11eb-8c06-c146c43118d1.png)


I should probably mention that the starting conditions were sampled, not identical. Still, I'd say, not much of a difference. Naively, I'd expect a symplectic integrator to outperform the EulerIntegrator ... what do you think?

**Comment by ElliotB256** [comment]
Yeah it should have better accuracy than the `EulerIntegrationSystem` for this problem. I would verify that the correct values of position and velocity are being used for the calculation.

We are using the approach here which eliminates the half-step velocity.
https://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet

**Comment by d-garrick** [comment]
I found that the velocity verlet was using `oldforce` to calculate positon where it should have been using `force`, since `force` already has the value of the force from the previous step. This improved heating rates for me but did not eliminate them entirely, so I have pushed the fix but won't yet mark the issue closed.

@MauriceZeuner Try the new version and see if it improves matters for you.

**Comment by MauriceZeuner** [comment]
![image](https://user-images.githubusercontent.com/73487591/113879719-b913fd80-97b2-11eb-95e6-7e8af09eccc7.png)
Thanks for your quick fix - unfortunately it seems, not too much has changed. I have plotted again for a timestep of 1 µs:
- orange: Euler Integration
- light blue: "old" velocity verlet before your fix
- vile pink/violett: "new" velocity-verlet 

could you give a bit more detail how you measured the improvement in heating rate and how significant it was? This still seems to be a very significant effect - not saying it -must- be the integration system at fault here but it seems logical since a reduction of the time-step (for example to 0.1 µs) drastically improves this and even after that (to 10 ns) an improvement is measurable. For a symplectic integration, this seems odd to me.

**Comment by d-garrick** [comment]
@MauriceZeuner Can you send me the code you are using? I've run some more tests on my end and in a harmonic trap of period 5ms, when a stationary atom is dropped from 1um, even a timestep of 1ms doesn't lead to heating. See below plots of atom position and velocity at timesteps of 0.01 and 1ms. The simulation runs until 300ms but I've cut the plots to 150ms to make them easier on the eyes.
![image](https://user-images.githubusercontent.com/78102623/113902351-b079f200-97c7-11eb-945a-9b48995a055d.png)

**Comment by ElliotB256** [comment]
Removed the warning label because bug is sufficient

**Comment by MauriceZeuner** [comment]
Hm, I am utterly confused. When I wanted to put together my minimum example for you to see it, the effect was not present. I now boiled it down to... well, I don't get how this should affect it in any way but... the `CentralCreator` - I compared it side-by side with a hard-coded atom and it appears to be the problem. I just don't get why since the atoms created that way have exactly the same components! 

I'll keep you updated but I think it's not the integration anymore.

**Comment by MauriceZeuner** [comment]
forget everything I said in that last post. I'll provide a good minimum example that shows the effect.

**Comment by ElliotB256** [comment]
Leave the posts anyway, no need to delete!

**Comment by MauriceZeuner** [comment]
Okay, here the minimum example that I promised comes: 

The example file in the dipole branch called "xodt_minimum_example.rs"  contains the following setup: 
1 Atom is "manually" (could also be a source entity but for the sake of providing a "minimum" example it's just that) added to the simulation, with no speed but a position different than zero. Then the simulation runs for a certain amount of time. 

If you do that for different 'TimeStep' resources, you get the following: 
<img src="https://user-images.githubusercontent.com/73487591/114473350-f4b42a80-9beb-11eb-8d1a-3559f0fe6805.png" width="500">

As you can see, a very strong heating effect is clearly visible on even these relatively short timescales. For the "finer" TimeSteps it simply takes way longer until this effect becomes visible, but it is still there.

Maybe a word about the dipole implementation so far: All relevant features for this minimum example are unit-tested, although sometimes not in the most professional way, which I plan to change. As a rule of thumb, the working principle is very similar to the concept of the 'CoolingLight' idea and laser module.

Don't hesitate if you have any questions about that part - I'm quite curious what you think where the heating comes from, no matter what's the reason.

Thanks!
Maurice

**Comment by d-garrick** [comment]
I may have found the problem - on the dipole branch, the integrator appears to be the old, incorrect version of velocity verlet:
    
```
pub struct VelocityVerletIntegrationSystem;

	fn run(
		&mut self,
		(mut pos, mut vel, t, mut step, force, mut oldforce, mass): Self::SystemData,
	) {
		use rayon::prelude::*;
		use specs::ParJoin;

		step.n = step.n + 1;
		let dt = t.delta;

		(&mut pos, &mut vel, &mut oldforce, &force, &mass)
			.par_join()
			.for_each(|(mut pos, mut vel, mut oldforce, force, mass)| {
				pos.pos = pos.pos
					+ vel.vel * dt + force.force / (constant::AMU * mass.value) / 2.0
					* dt * dt;
				vel.vel = vel.vel
					+ (force.force + oldforce.0.force) / (mass.value * constant::AMU) / 2.0 * dt;
				oldforce.0 = *force;
			});
	}
}
```


The correct version has to split the velocity and position integration into separate half-steps, as seen on the master:

```
pub struct VelocityVerletIntegratePositionSystem;
impl<'a> System<'a> for VelocityVerletIntegratePositionSystem {
	type SystemData = (
		WriteStorage<'a, Position>,
		ReadStorage<'a, Velocity>,
		ReadExpect<'a, Timestep>,
		WriteExpect<'a, Step>,
		ReadStorage<'a, Force>,
		WriteStorage<'a, OldForce>,
		ReadStorage<'a, Mass>,
	);

	fn run(&mut self, (mut pos, vel, t, mut step, force, mut oldforce, mass): Self::SystemData) {
		use rayon::prelude::*;
		use specs::ParJoin;

		step.n = step.n + 1;
		let dt = t.delta;

		(&mut pos, &vel, &mut oldforce, &force, &mass)
			.par_join()
			.for_each(|(mut pos, vel, mut oldforce, force, mass)| {
				pos.pos = pos.pos
					+ vel.vel * dt + force.force / (constant::AMU * mass.value) / 2.0
					* dt * dt;
				oldforce.0 = *force;
			});
	}
}

pub const INTEGRATE_VELOCITY_SYSTEM_NAME: &str = "integrate_velocity";

pub struct VelocityVerletIntegrateVelocitySystem;
impl<'a> System<'a> for VelocityVerletIntegrateVelocitySystem {
	type SystemData = (
		WriteStorage<'a, Velocity>,
		ReadExpect<'a, Timestep>,
		ReadStorage<'a, Force>,
		ReadStorage<'a, OldForce>,
		ReadStorage<'a, Mass>,
	);

	fn run(&mut self, (mut vel, t, force, oldforce, mass): Self::SystemData) {
		use rayon::prelude::*;
		use specs::ParJoin;

		let dt = t.delta;

		(&mut vel, &force, &oldforce, &mass).par_join().for_each(
			|(mut vel, force, oldforce, mass)| {
				vel.vel = vel.vel
					+ (force.force + oldforce.0.force) / (constant::AMU * mass.value) / 2.0 * dt;
			},
		);
	}
}
```

I think if you merge the master into your dipole branch, this problem will be fixed.

**Comment by MauriceZeuner** [comment]
No change... I just merged master into dipole again. The diagrams and the raw data look exactly the same. You can reproduce the result by switching to the dipole branch and just running:

'cargo run --release --example xodt_minimum_example'

**Comment by d-garrick** [comment]
The other thing you may need to do is explicitly give the integrator the correct dependencies - your dipole force will probably need to depend on the position integrator and the velocity integrator needs to depend on your dipole force, to ensure these systems are applied in the correct order.

**Comment by d-garrick** [comment]
did you push the merged branch? I just pulled dipole-force and it still has the old integrator.

**Comment by MauriceZeuner** [comment]
Something is weird. Even after merging master to dipole it still looks old...

**Comment by MauriceZeuner** [comment]
yes, I pushed everything.

**Comment by MauriceZeuner** [comment]
could this be a problem? How is it possible that only the reversion of a merge affects a file but not the merge itself?
![image](https://user-images.githubusercontent.com/73487591/114543466-26131180-9c51-11eb-8ce9-11ccd677b6f8.png)

**Comment by ElliotB256** [comment]
https://github.com/TeamAtomECS/AtomECS/commit/3f4ad52a0fc5c08c5ca716712f45f4b0851f32b3 

This one also appears to have stripped out the CI and other more recent changes

**Comment by MauriceZeuner** [comment]
Looks good now - huge thank you for your help. Still don't quite understand which part of git I used incorrectly - always thought merging and then reverting the merge commit would sum up to zero change - but that's apparently not the case.

I know, it's unprofessional, but for now, I created the branch: new-dipole-force based on master and manually pasted all relevant changes to it. The original branch is utterly broken and relevant parts from master are missing although it says it's update with master.

No unnatural heating is visible anymore, thank you!

**Comment by ElliotB256** [comment]
I think you must have made a commit at some point after the master branch which reversed the changes - so it thinks it is up to date in that all commits from master have been applied, but there is a commit on the branch which undoes some of these changes.
