### ISSUE TITLE
Dipole Trap asymetrical heating

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#27]
Hi all,

sorry for being quiet - I have been desperately trying to find the cause for a heating effect which seems to be still in the code but is most likely a dipole trap specific feature. I apologize in advance, this is super nasty and I'd be glad for new ideas how this could happen. 

First observation: If you simply put atoms in a dipole trap, but also have some CoolingLight Entities in the game, however, very far detuned, so they shouldn't do anything - you'll notice that there appears to be a preferred direction for their escape - the x-direction. It can best be observed in the (branch: new-dipole-force) cross_beam_dipole_trap.rs example - where there should be no difference between x and y since we have two identical, horizontal beams in exactly these two directions (and the MOT beams are on the diagonals). However, if you plot the absolute coordinate values of the ensemble (or just have a very sharp eye when plotting the data in 3D in Blender) you'll see that they are more likely to be further away from the centre in (plus or minus) x-direction.

![image](https://user-images.githubusercontent.com/73487591/115896852-c0463700-a453-11eb-8353-d9d571b38ac0.png)

In addition to that, there is still a good amount of numerical heating happening on top of that, this effect, however can be reduced by increasing the detuning of the MOT beams even further: 

![image](https://user-images.githubusercontent.com/73487591/115897145-069b9600-a454-11eb-88a2-de6cdf5abceb.png)

Before you ask: I checked in a pure symmetrical 3D MOT if there was a difference between x and y and I don't think it is present there. Of course, I also checked the way the dipole force is calculated for any symmetry breaking but couldn't find one. At that point, however, I am running a bit out of ideas where to look for it.

For comparison, here are the same diagrams as above just without any CoolingLight entities in the code: 
![image](https://user-images.githubusercontent.com/73487591/115897720-a35e3380-a454-11eb-8a02-52c59ce57c15.png)
![image](https://user-images.githubusercontent.com/73487591/115897768-ae18c880-a454-11eb-96be-7e3761f32289.png)

How did I find this behaviour in the first place? Well, I was running MOT -> DipoleTrap transitions with three stages:

1. MOT only (first 0.2 s)
2. MOT ramp down (power and detuning) (another 0.2s)
3. Dipole only - CoolingLight entities are deleted - (rest 1.4 s)

(see file: example/red_mod_xodt_transition.rs)

which looks like this: 
![image](https://user-images.githubusercontent.com/73487591/115899148-511e1200-a456-11eb-9ec5-cfa9c96454d4.png)
and
![image](https://user-images.githubusercontent.com/73487591/115899767-1072c880-a457-11eb-9751-eb1de9276e34.png)

I'd be extremely grateful for any, even far-fetched, ideas what could cause this behaviour.

**Comment by ElliotB256** [comment]
> however, very far detuned, so they shouldn't do anything

what detuning are you using? perhaps you could quick plot the offset versus detuning?

**Comment by ElliotB256** [comment]
Also, to verify that the cooling light is the cause - what happens if you change the direction of the cooling light?

**Comment by MauriceZeuner** [comment]
what would you change it to?

**Comment by MauriceZeuner** [comment]
Hang on. Sorry, this does exist on the master branch and for the red MOT also: 

![image](https://user-images.githubusercontent.com/73487591/115901844-a576c100-a459-11eb-8743-80007daaa59c.png)

**Comment by MauriceZeuner** [comment]
See branch asymmetric-heating and then example file: red_mot_from_center

**Comment by MauriceZeuner** [comment]
Ha! But not for the blue MOT!

![image](https://user-images.githubusercontent.com/73487591/115903664-c213f880-a45b-11eb-9b5d-4ba7e7b33e18.png)

So it's a red MOT specific problem.

**Comment by ElliotB256** [comment]
Can you provide a minimum example that produces the behaviour?

**Comment by MauriceZeuner** [comment]
yes, already have: 36da241

**Comment by MauriceZeuner** [comment]
plug in the transitions for the Blue MOT, change power and detuning to something that makes sense and you don't get the effect. 
It's only for the red MOT, it seems. If you don't trust the CentralCreator, I can also explicitly create random atoms in the center, but I think that's not the reason. (Since there's no problem with the blue MOT)

**Comment by MauriceZeuner** [comment]
Found, that the x-direction receives about 26% more force than y. By that, I mean the summed, absolute values in each direction. In a symmetrical setup, the forces should be equally strong. I investigated it using: a1c0f12

**Comment by MauriceZeuner** [comment]
I think I'm getting closer. RateCoefficients seem to be imbalanced too, not by much, though:

  ┌                                   ┐
  │  4396097345004.737 │ +z
  │ 3880732997761.6094 │ -z
  │  4601255035803.305 │ +x
  │  4631279125587.867 │ -x
  │  4417368384127.704 │ +y
  │  4331600239418.176 │ -y
  └                                   ┘

see
4b53446

I think this is rather a symptom (of being more offset from the centre in that direction) than a cause. But will investigate further.

**Comment by ElliotB256** [comment]
It might help to measure the rate coefficients for atoms placed at well-defined positions?

**Comment by MauriceZeuner** [comment]
Sorry, have to retract my last observation. Still had a 100µm offset in z for the magnetic field. RateCoefficients are sound:

pos: Vector3::new(5.0e-4, 5.0e-4, 5.0e-4)
  ┌                    ┐
  │   7835.07551271332 │
  │ 24398.235402460607 │
  │ 16297.298995739506 │
  │  24578.87894061315 │
  │ 16297.298995739506 │
  │  24578.87894061315 │
  └                    ┘

pos: Vector3::new(5.0e-4, 0.0e-4, 0.0e-4)
  ┌                    ┐
  │ 486199.11196358874 │
  │ 486199.11196358874 │
  │  9044.374930279317 │
  │ 1911505.4929097523 │
  │ 486199.11196358874 │
  │ 486199.11196358874 │
  └                    ┘

pos: Vector3::new(0.0e-4, 0.0e-4, 0.0e-4)
  ┌                    ┐
  │ 31767.037170127885 │
  │ 31767.037170127885 │
  │ 31767.037170127885 │
  │ 31767.037170127885 │
  │ 31767.037170127885 │
  │ 31767.037170127885 │
  └                    ┘
  
  But the heating and asymmetry remain.

**Comment by ElliotB256** [comment]
can you comment on whether the numbers above are expected? particular element 0 of the first one, and elements 3 and 4 of the second one

**Comment by MauriceZeuner** [comment]
yes, everything is as one would expect. the position is given above the vectors and the elements denote the entries of the RateCoefficients component. The first two are plus and minus z, 3 and 4 are x, 5 and 6 are y

**Comment by MauriceZeuner** [comment]
Just placed a single atom in the trap centre (static!). Summed force over 100000 time steps is:

  ┌                                      ┐
  │ 0.0000000000000000014452095452848004 │
  │ 0.0000000000000000011562930341955761 │
  │ 0.0000000000000000010981273888407856 │
  └                                      ┘

meaning, x is still getting more force even in that example. So we know it is somewhere between the RateCoefficients (which work fine) and the Force - which does not work fine. Also, it is (at least not alone) the integration system.

**Comment by MauriceZeuner** [comment]
It's not the ExpectedPhotonsScatteredVector either, that one is fine!

That only leaves the drawing from the Poisson distribution and the two ForceSystems

**Comment by ElliotB256** [comment]
Looking at these vectors with all that wasted precision does make me feel sad :D I wish the `uom` crate was able to work with Vectors. Maybe I can do something with macros to get it working - it's a really nice crate if we can use it, and it also does compile-time dimensional analysis.

**Comment by MauriceZeuner** [comment]
What wasted precision do you mean? The leading zeroes? It's just a println! command, not a value from a debugger (VS Code's debugger does not work for some reason...)

**Comment by MauriceZeuner** [comment]
Okay, it appears to be a problem that exists when both (!) the EmissionForceOption and the ScatteringFluctuationsOption are active. Summed force vector for static, central atom after 10,000,000 steps:

no emission force, only scattering fluctuations
  ┌                                   ┐
  │ 0.0000000000000000732180549846602 │  x
  │ 0.00000000000000007321997707152613 │ y
  │ 0.00000000000000007307005429598201 │ z
  └                                    ┘

only emission force, no fluctuations
  ┌   ┐
  │ 0 │x
  │ 0 │y
  │ 0 │z
  └   ┘

both!
  ┌                                    ┐
  │ 0.00000000000000016649020096496058 │x
  │ 0.00000000000000013291046326512055 │y
  │ 0.00000000000000013254777955999218 │z
  └                                    ┘

We can see that only in the last case (both activated) the x-direction gains significantly more force.

**Comment by MauriceZeuner** [comment]
Found the (or at least one) guilty! Its maths::random_direction(). For some reason it is more likely to spit out a vector with a larger absolute value in x.

**Comment by MauriceZeuner** [comment]
And the reason why it is important in red but not blue is that in blue, the function is called rarely since there are usually more than 5 photons scattered per step.

**Comment by ElliotB256** [comment]
ahh, interesting! is there a bug report for `random_direction` you can link?

**Comment by ElliotB256** [comment]
(and are you saying the discrepancies go away if you turn off fluctuations?)

**Comment by MauriceZeuner** [comment]
Yes, if you simply set laser::force::EmissionForceConfiguration::explicit_threshold to 0 (for the EmissionForceOption), the asymmetry is gone, hurray!  Not sure if all problems in the dipole trap are gone but in the master, that should solve the problem. To solve it a bit more sustainable, I recommend using a different method to obtain random vectors. Looking at the function it is actually quite obvious why it does not produce homogenous results. 

What do you mean by bug report? Is that another github feature I don't know about?

**Comment by ElliotB256** [comment]
Hmm, I didn't realise we were defining our own function for it! I assumed we were using one from another crate. Can you replace ours with https://docs.rs/rand_distr/0.4.0/rand_distr/struct.UnitSphere.html ?

**Comment by MauriceZeuner** [comment]
yes, will do that. Should I make that change directly on master?

**Comment by MauriceZeuner** [comment]
Hm, the heating for the dipole trap remains, but at least it is now symmetrical. 

So I guess, problem 1 out of 2 solved.

**Comment by ElliotB256** [comment]
If it only occurs when you do actually have random kicks drawn (ie, photons scattered), then are you sure the heating is unphysical? There is still some scattering rate for a far-detuned trap - what is the scattering rate you expect given your parameters and what is the associated heating rate?

**Comment by MauriceZeuner** [comment]
yes, because I did not give my dipole Lasers a "CoolingLight" component so far - so they should not be able to scatter at all, I think.

**Comment by ElliotB256** [comment]
Can you verify if it is integration error by reducing timestep by a factor of ten and running the same simulation time?

**Comment by MauriceZeuner** [comment]
![image](https://user-images.githubusercontent.com/73487591/116235510-dc005480-a755-11eb-863c-f489ebd0735c.png)

It's not an integration error, I'm pretty convinced. Just for reference:

A: startup phase, red MOT only
B: Switch on Dipole, start ramping down MOT
C: Dipole only, switch off red MOT completely

diagram shows distance from center for all particles

**Comment by MauriceZeuner** [comment]
My best guess is that something goes wrong when I switch off the MOT

**Comment by ElliotB256** [comment]
Sounds like you'll have to go through the systems one by one until you find the cause

**Comment by MauriceZeuner** [comment]
Found the problem: In short, the problem was that various components attached to the atoms were not cleared when the CoolingLight components are deleted. The `ApplyEmissionForceSystem` now runs despite no CoolingLight components (entities with them) are present anymore because it takes that information from the `ActualPhotonsScatteredVector` which still contains non-cero values from the time when the Laser beams were still active.

Ultimately I propose, we should create a clean, general System or method that clears component data of entities that are deleted, especially beams. And, for runtime reasons, also leads to irrelevant systems not running without any use. 

So far I have only made the hotfix to my dipole example code which basically turns off the `ApplyEmissionForceSystem` after the MOT-beams are deleted.

**Comment by ElliotB256** [comment]
Good find! I think a few things are confused here though.

First, if you delete an entity the associated components are removed once you call world.maintain. For example, from the [delete](https://docs.rs/specs/0.9.5/specs/struct.EntitiesRes.html#method.delete) doc:
> Deletes an entity atomically. The associated components will be deleted as soon as you call `World::maintain`.

It sounds like the bug is really in the formulation of the system logic. Looking at the systems, the following system clear out the values at the start of the frame:
```
pub struct InitialiseExpectedPhotonsScatteredVectorSystem;
impl<'a> System<'a> for InitialiseExpectedPhotonsScatteredVectorSystem {
    type SystemData = (WriteStorage<'a, ExpectedPhotonsScatteredVector>,);
    fn run(&mut self, (mut expected_photons,): Self::SystemData) {
        use rayon::prelude::*;
        use specs::ParJoin;

        (&mut expected_photons).par_join().for_each(|mut expected| {
            expected.contents =
                [ExpectedPhotonsScattered::default(); crate::laser::COOLING_BEAM_LIMIT];
        });
    }
}
```
If no lasers exist, this values should remain at the default (zero) value. However, it seems this system wasn't added to the dispatcher! Could you check into this for `master`?

**Comment by ElliotB256** [comment]
Closed because bug was found and new issue opened
