### ISSUE TITLE
Polarizability/E-field treatment instead of AtomicDipoleTransition

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#30]
Following a good discussion with Tiffany:

Especially for dipole trapping, it can actually become problematic to pretend the Atoms have only one transition that is relevant. For example, what if you have a dipole beam for Strontium, close to the red transition? You'd have to respect the blue because it has a huge linewidth but the red one also, because you are close. 

A far more realistic treatment would be to use polarizabilities instead and also E-fields instead of intensity gradients. I'd propose this as an enhancement for the foreseeable future. What do you think?

**Comment by ElliotB256** [comment]
Added in PR #57
