### ISSUE TITLE
User-friendly way to produce output of custom component

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#32]
I think it would be great to have a very simple way to write not only Position and Velocity to a textfile and analyse it in Python/Matlab but maybe a general `WriteComponentToFileSystem` that users can configure to write the values they are interested in.

For example: If I wanted to print the contents of the `TotalPhotonsScattered` component for all atoms over time, I might want to plot that against the `power` of all `GaussianBeam` entities. Currently (please correct me if I'm wrong) I write my own writer-system for that every time I need it and there exists no nice and most importantly run-time optimized way of doing that. (See the super-slow xyz-writer, ahem, ahem... ).

But especially if one wants to monitor all sorts of interesting parameters over complicated runs (red Sr-MOT to dipole transition, for example), it would be so cool to get that data printed to a text file in one line of code. 

What do you think?

**Comment by ElliotB256** [comment]
With the current approach, for a text output you need to implement Display for the component: 
```
pub struct Text {}
impl<C, W> Format<C, W> for Text
where
    C: Component + Clone + Display,
    W: Write,
{
```
then you can use it in a `file::new<Component, Text>()` to write those component values every frame.

Where it could be improved is that `Display` is probably not the best trait to use here. Ideally we would use existing serialization functionality for components, such as is provided by `serde`. If you could write a `file::Serde` struct that implements `Format` to serialize structs using the `serde` library, then we could just use the derive macros for `Serialize` to make every component type writable to a human-readable format. As an added bonus, you would benefit from the wide range of formats `serde` supports, each writing json, yaml, whatever people like.

**Comment by ElliotB256** [comment]
@MauriceZeuner it might be as simple as this:
```pub struct SerdeJson {}
impl<C, W> Format<C, W> for SerdeJson
where
    C: Component + serde::Serialize + Clone,
    W: Write,
{
    fn write_frame_header(writer: &mut W, step: u64, atom_number: usize) -> Result<(), io::Error> {
        write!(writer, "step-{:?}, {:?}\n", step, atom_number)?;
        Ok(())
    }

    fn write_atom(writer: &mut W, atom: Entity, data: C) -> Result<(), io::Error> {
        let serialized = serde_json::to_string(&data).unwrap();
        write!(
            writer,
            "{:?},{:?}, {}\n",
            atom.gen().id(),
            atom.id(),
            serialized
        )?;
        Ok(())
    }
}```

(Compiles, but I didn't get time to test it yet!)

**Comment by ElliotB256** [comment]
oh, also I have no idea about execution speed for serde, but we could benchmark it easy enough.

**Comment by ElliotB256** [comment]
See 62777bac52c443a01d443b99bbfce8a1f0c7d71a , which includes this

**Comment by ElliotB256** [comment]
@MauriceZeuner if you are bored and looking for things to work on then you could check this?

**Comment by MauriceZeuner** [comment]
Wouldn't say I'm bored but happy to look through it. ^^

**Comment by MauriceZeuner** [comment]
Looks good in principle but I have to place it somewhere else in the ECS order because it only prints 0-values for components that are cleared each step (like `Force`)

**Comment by MauriceZeuner** [comment]
Yes, so the following helps: 

`    builder = builder.with(
        file::new::<lib::atom::Force, SerdeJson>("force.txt".to_string(), 100),
        "",
        &[INTEGRATE_VELOCITY_SYSTEM_NAME],
    );`

So, it is necessary to wait for all the force systems to run (or do it before the `ClearForcesSystem`, but there is no nice entry point) and it works. Guess, it's the same for other components that are regularly cleared. The text output looks like this: 

`1,10806, {"force":[-1.0534468251559025e-21,-4.392138872181409e-21,1.5356417929484982e-78]}`

Are you happy with that?

**Comment by MauriceZeuner** [comment]
My next step would now be to add `Serialize` to other components and check how their output looks like. If that's fine and you don't mind that people have to import the `INTEGRATE_VELOCITY_SYSTEM_NAME` to do that, I think it can be merged onto master.

**Comment by ElliotB256** [comment]
yeah that sounds great. I wonder to what extent we can leave the serde implementation open? eg, someone may like to use json, while another may like to output in YAML format. There's probably a way to do it agnostic of the (de)serialization flavor used, but it might require a macro definition.

**Comment by MauriceZeuner** [comment]
I think I only understood half of what you said in detail :D Let me try:
Okay, so apparently there are two different ways of producing output files... meaning, converting internal storage structures to human-readable format... and we are currently doing json, right? But we write it to .txt files ... what exactly would be different with YAML?

What is a serialization flavor or a flavor at all?

By macros, you mean these things: https://doc.rust-lang.org/book/ch19-06-macros.html , right?

Is this (the "agnosticism regarding YAML or json") something we should take now or should we do so later and first finish the current approach with serdejson?

Sorry for asking so many questions...

**Comment by MauriceZeuner** [comment]
Do you have an idea how not to write entries in Vectors that are null (like the `DopplerShiftSamplers` for example)? Currently its output looks a bit ugly, but is, of course, correct:

`1,10307, {"contents":[{"doppler_shift":117297311.27240404},{"doppler_shift":-335276.52687008784},{"doppler_shift":-813804.8382839408},{"doppler_shift":813804.8382839408},{"doppler_shift":335276.52687008784},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null},{"doppler_shift":null}]}
`

**Comment by MauriceZeuner** [comment]
Another thing that came to mind: Currently, it's hard-coded to write the components of atoms only - nothing wrong with that in 99% of the cases, I guess but especially if we use ramps, wouldn't it be nice to also write some beam components?

**Comment by ElliotB256** [comment]
>  so apparently there are two different ways of producing output files
or better yet, there are arbitrarily many ways! Our structs implement serde's `Serialize` trait, which means any of serde's [supported Serialized types](https://serde.rs/#data-formats) are in principle supported.

The issue in the code I posted above is that it ties the implementation to `serde_json` when it invokes `serde_json::to_string`. In principle, you could imagine that any library could be substituted in there. One way to implement this could be to use a macro to generate the system implementation, so that any `serde` formatter could be used. Or you could have a generate implementation that declares a struct implementing a `Format` trait, which implements a `to_string` function. Then your use could look like eg `<Force, Serde, Json>`, where `Json` implements `Format`.

**Comment by ElliotB256** [comment]
> Do you have an idea how not to write entries in Vectors that are null
You could define a custom `Serialize` implementation for the struct, so it doesn't print the null elements.

> Currently, it's hard-coded to write the components of atoms only
Fair point! I wonder what the best way to change that is. We could expose `Atom` here as another generic parameter `A` and filter on that flag component type.

**Comment by MauriceZeuner** [comment]
Okay, I went ahead for the serdejson and exposed the `Atom` as the `A` parameter. I had to change that in the `Text` outputs as well, though, see https://github.com/TeamAtomECS/AtomECS/commit/964952eee67ba346d845966a09f0c95eda8853ca

**Comment by MauriceZeuner** [comment]
Any comments? If not I'd open a pull request so we can use it on other branches (that we derive from master) soon as well.

**Comment by MauriceZeuner** [comment]
Just updated documentation file.rs slightly, see a0b5c14

**Comment by ElliotB256** [comment]
Did you try a version using `Json` as a `Formatter`, eg to replace `Text`?

**Comment by MauriceZeuner** [comment]
Yes, just tested it. Had to implement Serialize for the `Velocity` (another micro-commit) but yes, exactly the same result as with `Text` but obviously with brackets and "vel" in front of it:
```
step-100, 8428
1,10, {"vel":[47.65330390301528,50.685040570013015,61.84040397595534]}
1,11, {"vel":[141.35281711667943,18.302264557360893,-5.391203664469684]}
1,12, {"vel":[124.2260904200673,3.203314605867649,15.447966003792397]}
1,14, {"vel":[134.3467111780397,33.42374275947403,69.00938481951157]}
1,18, {"vel":[30.868301336656614,48.46357081740587,20.294068316528016]}
1,19, {"vel":[132.2093168227528,32.76907598736442,-100.74824553701016]}
1,21, {"vel":[136.26820483685023,37.03645727159572,4.865025792455573]}
1,23, {"vel":[174.67866551660134,-11.242258619627972,19.446860426561503]}
1,24, {"vel":[183.41304116316667,15.566187743851604,22.90542691873729]}
```

**Comment by ElliotB256** [comment]
Sorry I forgot to reply on this, do you want to open a PR?

**Comment by ElliotB256** [comment]
#47
