### ISSUE TITLE
Polarization and Jones vector

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#37]
Just to let people know that I am working on extending the Gaussian beam description to correct treatment of (at least fully) polarized light with arbitrary ellipticity of the Jones vector. 

If you wonder why: Well, I think we do already have 50% of the stuff we need to model Sisyphus-cooling and I suppose that this would definitely be a nice feature in the mid-future. Any thoughts?

The branch will be "alternative-dipole-force" where I also switch to a full complex electric field treatment for dipole traps.

At the moment, I imagine it working like this: Your basic component always is the `LinearGaussianEBeam` and then you just add a (name provisional) `JonesVector` component to the beam entity. Since you can separate the rotation of the electric field vector and the other gaussian beam characteristics, you can then in a `SampleElectricFieldSystem` just (complex) multiply the jones vector (which is basically a rotation-operator) to the other terms of the gaussian E-field and you should get a (for example circularly) polarized gaussian beam.

For Sysiphus cooling I think, you should be able to get a standing wave in polarization (not intensity!) by just adding two counterpropagating beams with orthogonal polarization to the simulation. At positions where the counter-propagating beams have a phase difference of π/2  the polarization is circular, and where there is no phase difference, the polarization is linear. In the intermediate regions, there is a gradient elipticity of the superposed fields. 

What, of course would also be required for this to work (will be a separate issue, probably) is a slightly more complicated atom-component which can respect the important M_J substrates of the atom.

**Comment by ElliotB256** [comment]
(Closing duplicate issue, lets continue in #29)
