### ISSUE TITLE
Fine to use the `num = "0.4.0"` dependency for complex numbers?

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#38]
Would anyone object if we added the `num = "0.4.0"` to the list of project dependencies? It enables the use of complex numbers with:

`num::complex`

See: https://docs.rs/num-complex/0.4.0/num_complex/index.html

**Comment by ElliotB256** [comment]
sure, go for it. Add it on the branch you require the package and we will add it when we merge into master.
