### ISSUE TITLE
Update to latest `specs`

### ISSUE THREAD

**Issue by ElliotB256** [TeamAtomECS/AtomECS#42]
I need to update to the latest specs+rayon to fix the panic issue, so we can get back to nightly toolchain.

The specs API has some breaking changes, so I need to update all examples aswell.

**Comment by ElliotB256** [comment]
See 53f6adf47 - the main changes to add are:
* Use `specs::prelude::*` instead of individual trait/struct imports.
* change `world.add_resource` to `world.insert`
* Also took the opportunity to remove `extern crate specs` where possible.

I've fixed benchmarks, tests and examples. Tests pass and `atomecs` now runs on nightly toolchain again. I'll need to update the dependent repos (such as the source optimisation example).

**Comment by ElliotB256** [comment]
See PR #43 

I'll merge this in ASAP. @MauriceZeuner and damienBloch, could you update your branches to this version aswell?

**Comment by MauriceZeuner** [comment]
Help! Something in the merge went horribly wrong... there were a lot of conflicts but now every example file has this problem:
![image](https://user-images.githubusercontent.com/73487591/118821636-5896d680-b8af-11eb-9af8-9fed5a85fb2c.png)

**Comment by MauriceZeuner** [comment]
I thought I resolved all conflicts reasonably... but especially in the cargo.lock there were like 53 of them - just accepted the entire incoming file.

**Comment by ElliotB256** [comment]
did you try `cargo update`?

**Comment by ElliotB256** [comment]
Also you probably need to restart VS Code - the RLS is alright, but it does bug out from time to time (especially when there are large changes to packages). You can try restarting the RLS using Ctrl+shift+p and searching for RLS

**Comment by MauriceZeuner** [comment]
Okay, a combination of these things appears to have done the trick. Now for the painful process of changing the syntax in all files not on master... 

(meaning, the master examples now run again but of course, my own modules and examples don't, but shouldn't take too long)

**Comment by MauriceZeuner** [comment]
Alright, everything seems to be fine, now. Thanks for your help!

**Comment by ElliotB256** [comment]
Also @DavidGarrick will have to do this for collisions
