### ISSUE TITLE
There are some compiling error and more clippy warnings, I want to fix them

### ISSUE THREAD

**Issue by necokeine** [TeamAtomECS/AtomECS#62]
Hi here,

I am new to here, and I want to fix compiling and clippy first, if there is any other issues, I may take one.

**Comment by ElliotB256** [comment]
That would be very welcome, thank you for offering!

I could also add clippy to the CI to maintain going forward

**Comment by necokeine** [comment]
Thank you for your reply. I created a PR to fix compiling and some clippy.
I can help you to add some git hooks to this repo, is it what you want?

**Comment by ElliotB256** [comment]
If you have something alreayd that would be very useful, I can add some information to the getting started guide/guide for contributors to also tell them how to run clippy.

**Comment by ElliotB256** [comment]
PR merged!
