### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by minghuaw** [TeamAtomECS/AtomECS#63]
Are you considering publishing this on crates.io? There have been some "bad actors" who claims the crate's name by just publishing an empty crate on crates.io, and you should probably consider claiming this name to avoid any potential issues in the future?

**Comment by ElliotB256** [comment]
Thanks for the suggestion! I've done this now for the two important crates:
https://crates.io/crates/atomecs
https://crates.io/crates/atomecs-derive

**Comment by ElliotB256** [comment]
(I also updated version to 0.6.0 while we are here!)
