### ISSUE TITLE
Simplifying GaussianBeam power calculation in `from_peak_intensity`

### ISSUE THREAD

**Issue by minghuaw** [TeamAtomECS/AtomECS#69]
There are two problems though the converted power in the current implementation is correct.

## First question

https://github.com/TeamAtomECS/AtomECS/blob/f2a58047b5c8650c8b055f9ff0dba1cdd3296fda/src/laser/gaussian.rs#L71

Shouldn't the right hand side be multiplying `e_radius` by `sqrt(2)`?

https://github.com/TeamAtomECS/AtomECS/blob/f2a58047b5c8650c8b055f9ff0dba1cdd3296fda/src/laser/gaussian.rs#L72

Shouldn't the right hand side be like divide the product of `peak_intensity`, `pi` `e^2_radius` by 2 instead of multiplying it by 2?

Given that 

<img width="126" alt="Screen Shot 2021-12-16 at 7 33 07 PM" src="https://user-images.githubusercontent.com/29760666/146485842-7d196a58-0ff9-4dc7-a76d-9308dd7137d7.png"> ([Edmund's optics](https://www.edmundoptics.com/knowledge-center/application-notes/lasers/gaussian-beam-propagation/), [RP Photonics](https://www.rp-photonics.com/optical_intensity.html))

Rearranging would give 

<img width="128" alt="Screen Shot 2021-12-16 at 7 47 39 PM" src="https://user-images.githubusercontent.com/29760666/146485893-e55f9caf-243e-481c-b3d8-d3b41852164b.png">

## Second question

According to the documentation

https://github.com/TeamAtomECS/AtomECS/blob/f2a58047b5c8650c8b055f9ff0dba1cdd3296fda/src/laser/gaussian.rs#L37

making the changes suggested in Q1 would give the same result because following the suggestion above would give

<img width="535" alt="Screen Shot 2021-12-16 at 7 56 14 PM" src="https://user-images.githubusercontent.com/29760666/146486589-7662d9aa-b922-4d5c-ba2d-49444a3733fb.png">

And the current implementation is

<img width="491" alt="Screen Shot 2021-12-16 at 8 00 19 PM" src="https://user-images.githubusercontent.com/29760666/146486855-53fb49ec-12c8-41cf-be6d-7895ee1d2784.png">

which gives the same result. 

However, this leads to the problem of a small optimization where the square root and the multiply by two can be simply neglected.

**Comment by ElliotB256** [comment]
I think it depends on what you define as the waist, and there are a few different definitions. The current components are defined in terms of the '1/e *radius* of intensity', r_0, such that `I(r) = I_0 exp((-r / r_0)^2)`. A more common definition is the beam waist, w, taken such that this is the beam *diameter* over which the intensity is equal to `I_0 exp(-2)`. They differ by a factor of `2 sqrt(2)`. I haven't yet had a chance to review your numbers, but hope to soon.

**Comment by minghuaw** [comment]
The problem is not really with the waist definition. It's essentially redundant operations (divide by sqrt(2), take the square and then multiply by 2, which cancels out).

**Comment by BrianBostwick** [comment]
This is the is the same issue that we just closed @ElliotB256, I am going to create a pull request for this now.

**Comment by BrianBostwick** [comment]
Also, we can probably close this issue as well now.
