### ISSUE TITLE
Magnetic traps

### ISSUE THREAD

**Issue by ElliotB256** [TeamAtomECS/AtomECS#72]
Add support for magnetic traps.

For the purposes of this issue, this refers to traps where the potential energy can be written in the form `E = g_F \mu_B | B(r) |`, and where B is a real magnetic field. This includes static magnetic field traps, such as quadrupole traps, and traps where the magnetic field is slowly varying, e.g. Time-Orbiting Potential (TOP) traps.

This issue does not include support for RF-dressed traps (where the magnetic field is oscillating at a rate comparable to the Zeeman splitting).

**Comment by ElliotB256** [comment]
I've added this issue for a bit of book-keeping - it is already supported to some extent in the code but I'd like to have a place for discussion on the implementation and to associate features with the relevant milestones.

@d-garrick can you comment on whether the above is supported? I see also damien added a PR for magnetic fields in #54, which we delayed merging until the rest of the implementation was clear, but it would be good to either retire or merge the PR.

**Comment by d-garrick** [comment]
At the moment the magnetic field sampler calculates a magnetic field strength gradient at the position of each atom, so a trapping force can be calculated for any magnetic field that is defined. The only specific magnetic fields currently implemented are the quadrupole, TOP, and uniform field.
