### ISSUE TITLE
Plugin Workflow

### ISSUE THREAD

**Issue by ElliotB256** [TeamAtomECS/AtomECS#73]
`bevy` has a really nice implementation of 'Plugins', where you can define individual parts of a program to add/remove. A similar plugin model could be used in AtomECS to add different models of laser cooling, different forces, collisions, etc. This would improve the usability and increase program flexibility (possibly also performance by only running required/declared modules).

Related to #3.

**Comment by ElliotB256** [comment]
First draft in 37c286f

**Comment by minghuaw** [comment]
Is there any good reason that `Plugin::build` takes `&self` instead of `self`?

**Comment by ElliotB256** [comment]
Good point, it probably should be `self` - the plugin should be consumed by the process, not borrowed
