### ISSUE TITLE
detuning in molasses

### ISSUE THREAD

**Issue by YangChemE** [TeamAtomECS/AtomECS#77]
Hi, new user here. About the 1d molasses example, I'm wondering why is the detuning set as -6 for 87Rb, my understanding is that the unit of the detuning is MHz, and for the molasses of 87Rb atom farther detuning is usually used (compared to -20.8 for the MOT of 87Rb) in experiments. I did test farther detuning (eg, -80) and it did not work well, so I'm wondering what's behind this setting as I'm sure I have missed something. Thanks in advance!

**Comment by ElliotB256** [comment]
Hey there!

The units are in MHz, the examples are really just supposed to be bare minimum examples to show you how to use the program (it isn't neccessarily the best value for a molasses, for instance). When you say 'it did not work well', do have more details about the scenario you are trying to simulate? -80 MHz for Rb is about 13 linewidths away, so it won't have much of an affect on already slow moving atoms. We usually use a large detuning during our cMOT stage to reduce rescattering, but then there is also a (weak) magnetic field which allows even slow moving atoms to interact with the beams away from the trap centre.

(If you look in the tests, there is an example which compares the scattering rates to theory and shows good agreement between the two)

**Comment by YangChemE** [comment]
Thanks for the clarification!
