### ISSUE TITLE
Dipole trap frequency

### ISSUE THREAD

**Issue by BrianBostwick** [TeamAtomECS/AtomECS#79]
Hey @ElliotB256,

As you are aware, there has been an issue with the trap frequency for the dipole implementation. After some digging, I found a factor of 2 in the spot size definition for the gaussian beam. Removing this factor of 2, the trap frequencies agreed with the calculated trap frequencies. 

The issue seems to be line 234 of gassian.rs in get_gaussian_beam_intensity_gradient:
        **2.0**  * beam.e_radius.powf(2.0) * (1. + (z / beam.rayleigh_range).powf(2.0));

Why is there this factor of 2 out front?

**Comment by ElliotB256** [comment]
Not sure, you would have to check with @MauriceZeuner https://github.com/TeamAtomECS/AtomECS/blame/34f67e7b4e837d8535710937fc6b841347091fef/src/laser/gaussian.rs#L234

**Comment by BrianBostwick** [comment]
Okay, thank you. @MauriceZeuner, is there a particular reason there is an extra factor of two here?

**Comment by ElliotB256** [comment]
Could the factor of two be related to some inconsistent definition of physical parameters somewhere, eg beam waist diameter versus radius or some polarisation of the light? Brian, perhaps you could post your workings for future readers to see?

(As an aside, the unit test for dipole should be changed - it looks like Maurice used whichever values it produced at the time, presumably after checking it though? let's see what he says)

**Comment by BrianBostwick** [comment]
It seems like there are two places where there was an extra factor of two. After removing them I get the result that is consistent with the trap frequencies after making the harmonic potential approximation. 

This is how get_gaussian_beam_intesity_gradient() is currently defined in /src/laser/gaussian.rs as, 

```
pub fn get_gaussian_beam_intensity_gradient(
    beam: &GaussianBeam,
    pos: &Position,
    reference_frame: &Frame,
) -> Vector3<f64> {
    let rela_coord = pos.pos - beam.intersection;

    // ellipticity treatment
    let semi_major_axis = 1.0 / (1.0 - beam.ellipticity.powf(2.0)).powf(0.5);

    let x = rela_coord.dot(&reference_frame.x_vector) / semi_major_axis.powf(0.5);
    let y = rela_coord.dot(&reference_frame.y_vector) * semi_major_axis.powf(0.5);
    let z = rela_coord.dot(&beam.direction);

    let spot_size_squared =
        2.0 * beam.e_radius.powf(2.0) * (1. + (z / beam.rayleigh_range).powf(2.0));
    let vector = -4. * (reference_frame.x_vector * x + reference_frame.y_vector * y)
        + beam.direction * z / (beam.rayleigh_range.powf(2.0) + z.powf(2.0))
            * (-spot_size_squared + 4. * (x.powf(2.0) + y.powf(2.0)));
    let intensity = 2. * beam.power / PI / spot_size_squared
        * EXP.powf(-2. * (x.powf(2.0) + y.powf(2.0)) / spot_size_squared);

    intensity / spot_size_squared * vector
}
```

There is 2.0 in front of spot size which I don't believe should be there as this adds a sqrt(2) to the beam waist definition. But if you remove this then the radial trap frequency is exactly double what it should be and so it looked the issue was because of this factor of 4.0 in front of the the x and y reference frame vectors. After changing the above code to the follwoing,

```
pub fn get_gaussian_beam_intensity_gradient(
    beam: &GaussianBeam,
    pos: &Position,
    reference_frame: &Frame,
) -> Vector3<f64> {
    let rela_coord = pos.pos - beam.intersection;

    // ellipticity treatment
    let semi_major_axis = 1.0 / (1.0 - beam.ellipticity.powf(2.0)).powf(0.5);

    let x = rela_coord.dot(&reference_frame.x_vector) / semi_major_axis.powf(0.5);
    let y = rela_coord.dot(&reference_frame.y_vector) * semi_major_axis.powf(0.5);
    let z = rela_coord.dot(&beam.direction);

    let spot_size_squared =
        beam.e_radius.powf(2.0) * (1. + (z / beam.rayleigh_range).powf(2.0));
    let vector = -1.0 * (reference_frame.x_vector * x + reference_frame.y_vector * y)
        + beam.direction * z / (beam.rayleigh_range.powf(2.0) + z.powf(2.0))
            * (-spot_size_squared + 4. * (x.powf(2.0) + y.powf(2.0)));
    let intensity = 2. * beam.power / PI / spot_size_squared
        * EXP.powf(-2. * (x.powf(2.0) + y.powf(2.0)) / spot_size_squared);

    intensity / spot_size_squared * vector
}
```
everything seems to work as expected. So I was wondering If this was a mistake or is it intentional and compensating for something else that the dipole trap is not currently using.

**Comment by BrianBostwick** [comment]
Update to the previous post.

After more digging with @cahty1006, we found that the issue was not the spot size but a factor of two in the vector definition. Here is what we believe the code should look like. 

```
pub fn get_gaussian_beam_intensity_gradient(
    beam: &GaussianBeam,
    pos: &Position,
    reference_frame: &Frame,
) -> Vector3<f64> {
    let rela_coord = pos.pos - beam.intersection;

    // ellipticity treatment
    let semi_major_axis = 1.0 / (1.0 - beam.ellipticity.powf(2.0)).powf(0.5);

    let x = rela_coord.dot(&reference_frame.x_vector) / semi_major_axis.powf(0.5);
    let y = rela_coord.dot(&reference_frame.y_vector) * semi_major_axis.powf(0.5);
    let z = rela_coord.dot(&beam.direction);

    let spot_size_squared =
        2.0*beam.e_radius.powf(2.0) * (1. + (z / beam.rayleigh_range).powf(2.0));
    let vector = -4.0 * (reference_frame.x_vector * x + reference_frame.y_vector * y)
        + beam.direction * z / (beam.rayleigh_range.powf(2.0) + z.powf(2.0))
            * (-2.0*spot_size_squared + 4. * (x.powf(2.0) + y.powf(2.0)));
    let intensity = 2. * beam.power / PI / spot_size_squared
        * EXP.powf(-2. * (x.powf(2.0) + y.powf(2.0)) / spot_size_squared);

    intensity / spot_size_squared * vector
}
```

**Comment by ElliotB256** [comment]
Hi Brian,

It looks like the existing unit tests were not updated, so the program currently fails to pass tests. Could you push a fix for merging? (I think it's just the factor of two needs updating in the unit test aswell)

Thanks!
Elliot
